# Generated by Django 3.0.5 on 2020-04-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_comment_discussion_forum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
        migrations.AddField(
            model_name='forum',
            name='categories',
            field=models.CharField(default='Вода|Электричество|Другое', max_length=100),
        ),
        migrations.AlterField(
            model_name='forum',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.Company'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='house',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.House'),
        ),
    ]
