# Generated by Django 3.0.5 on 2020-04-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_auto_20200410_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='anon_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
