# Generated by Django 3.0.5 on 2020-04-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_auto_20200415_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='description',
        ),
    ]
