# Generated by Django 3.0.3 on 2020-04-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_auto_20200417_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.IntegerField(),
        ),
    ]
