# Generated by Django 3.0.3 on 2020-04-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_auto_20200417_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='company',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='creator',
            field=models.TextField(default='tenant'),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default='message'),
            preserve_default=False,
        ),
    ]
