# Generated by Django 2.2.11 on 2020-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0011_auto_20200417_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='description',
            field=models.TextField(default='описание'),
            preserve_default=False,
        ),
    ]
