# Generated by Django 3.0.3 on 2020-04-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_discussion_description'),
        ('tenant', '0008_auto_20200415_1359'),
    ]

    operations = [
    ]
