# Generated by Django 3.0.3 on 2020-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0013_merge_20200418_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='anon_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
