# Generated by Django 3.0.3 on 2020-04-22 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0015_auto_20200418_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('creator', models.TextField(default='tenant')),
                ('cr_date', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='HelpDesk',
            new_name='Appeal',
        ),
        migrations.DeleteModel(
            name='HelpDeskSmartMessage',
        ),
        migrations.AddField(
            model_name='appealmessage',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.Appeal'),
        ),
    ]
