# Generated by Django 3.0.3 on 2020-05-02 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0018_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='volunteer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_vol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='test_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.House'),
        ),
    ]
