# Generated by Django 3.0.5 on 2020-05-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0019_auto_20200502_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
