# Generated by Django 3.0.5 on 2020-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0020_tenant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='photo',
            field=models.ImageField(blank=True, default='static/default.jpg', upload_to='photo'),
        ),
    ]
