# Generated by Django 3.0.5 on 2020-05-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0022_auto_20200507_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='address',
        ),
    ]
