# Generated by Django 3.0.5 on 2020-05-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0024_auto_20200508_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='flat',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='tenant',
            name='house_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
