# Generated by Django 3.0.6 on 2020-05-15 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0024_auto_20200508_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_date', models.DateTimeField()),
                ('status', models.TextField()),
                ('target', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('patronymic', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('aim', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
