# Generated by Django 3.0.5 on 2020-05-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0025_auto_20200516_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='flat',
            field=models.TextField(),
        ),
    ]
