# Generated by Django 3.0.5 on 2020-05-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0025_auto_20200516_1104'),
        ('tenant', '0025_pass'),
    ]

    operations = [
    ]
