# Generated by Django 3.0.5 on 2020-05-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0027_auto_20200516_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anon',
            field=models.BooleanField(default=False),
        ),
    ]
