# Generated by Django 3.0.5 on 2020-05-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0028_comment_anon'),
        ('tenant', '0026_auto_20200516_1453'),
    ]

    operations = [
    ]
