# Generated by Django 3.0.5 on 2020-05-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0029_merge_20200516_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='thread',
        ),
    ]
