# Generated by Django 3.0.5 on 2020-05-20 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0029_merge_20200516_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='manager_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Antosha')),
                ('surname', models.TextField(default='Andreev')),
                ('status', models.IntegerField(choices=[(1, 'Accepted'), (2, 'Refused'), (3, 'Not considered')], default=3)),
                ('inn', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
