# Generated by Django 3.0.5 on 2020-05-20 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0030_auto_20200520_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='manager_request',
            new_name='ManagerRequest',
        ),
        migrations.RenameField(
            model_name='managerrequest',
            old_name='inn',
            new_name='inn_company',
        ),
    ]
