# Generated by Django 3.0.5 on 2020-05-21 17:13

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0030_remove_comment_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text1',
            field=martor.models.MartorField(default='#HEADER'),
            preserve_default=False,
        ),
    ]
