# Generated by Django 3.0.5 on 2020-05-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0031_auto_20200520_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='company',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='tenant.Company'),
        ),
    ]
