# Generated by Django 3.0.5 on 2020-05-21 17:30

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0031_comment_text1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text1',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=martor.models.MartorField(),
        ),
    ]
