# Generated by Django 3.0.5 on 2020-05-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0032_auto_20200520_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.Company'),
        ),
    ]
