# Generated by Django 3.0.5 on 2020-05-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0033_auto_20200520_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.TextField(default=False),
        ),
    ]
