# Generated by Django 3.0.5 on 2020-05-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0032_auto_20200521_1730'),
        ('tenant', '0033_auto_20200520_1958'),
    ]

    operations = [
    ]
