# Generated by Django 3.0.5 on 2020-05-22 13:25

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0034_merge_20200522_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealmessage',
            name='text',
            field=martor.models.MartorField(),
        ),
    ]
