# Generated by Django 3.0.5 on 2020-05-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0035_auto_20200522_1325'),
        ('tenant', '0034_company_name'),
    ]

    operations = [
    ]
