# Generated by Django 3.0.5 on 2020-05-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0036_merge_20200522_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(),
        ),
    ]
