# Generated by Django 3.0.5 on 2020-05-24 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0038_comment_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.Discussion'),
        ),
    ]
