# Generated by Django 3.0.6 on 2020-05-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0039_auto_20200524_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
