# Generated by Django 3.0.5 on 2020-05-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tenant', '0041_auto_20200525_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ya_num',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
