# Generated by Django 3.0.5 on 2020-05-25 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tenant', '0042_auto_20200525_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ya_num',
        ),
    ]
