# Generated by Django 3.0.5 on 2020-05-25 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tenant', '0045_auto_20200525_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ya_num',
        ),
    ]
