# Generated by Django 3.0.5 on 2020-05-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tenant', '0047_company_ya_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ya_num',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
