# Generated by Django 3.0.5 on 2020-05-25 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tenant', '0048_auto_20200525_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ya_num',
        ),
    ]
