# Generated by Django 3.0.5 on 2020-05-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tenant', '0049_remove_company_ya_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ya_num',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
