# Generated by Django 3.0.5 on 2020-05-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tenant', '0050_company_ya_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ya_num',
            field=models.IntegerField(),
        ),
    ]
