# Generated by Django 3.0.3 on 2020-03-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
