# Generated by Django 3.0.3 on 2020-04-18 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0003_delete_feedback'),
        ('common', '0002_company_house_manager_tennant'),
    ]

    operations = [
    ]
