# Generated by Django 3.0.3 on 2020-05-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_merge_20200418_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='company',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='company',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tennant',
            name='house',
        ),
        migrations.RemoveField(
            model_name='tennant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Tennant',
        ),
    ]
