# Generated by Django 3.0.3 on 2020-05-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200503_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourmail', models.EmailField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('mail', models.EmailField(max_length=50)),
                ('finished', models.BooleanField()),
                ('title_back', models.CharField(max_length=50)),
                ('text_back', models.CharField(max_length=50)),
            ],
        ),
    ]
