# Generated by Django 3.0.5 on 2020-06-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20200603_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.TextField(default='kek'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='surname',
            field=models.TextField(default='kek'),
        ),
    ]
