# Generated by Django 3.0.5 on 2020-06-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20200603_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='admin',
            name='surname',
            field=models.TextField(default=' '),
        ),
    ]
