# Generated by Django 3.0.6 on 2020-05-30 12:50

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicationDate', models.DateTimeField(verbose_name='date published')),
                ('publicationTitle', models.CharField(max_length=50)),
                ('publicationText', martor.models.MartorField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.Company')),
            ],
        ),
    ]
