# Generated by Django 3.0.6 on 2020-06-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='district',
        ),
        migrations.RemoveField(
            model_name='news',
            name='publicationTag',
        ),
    ]
