# Generated by Django 3.0.5 on 2020-05-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_manager_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
