# Generated by Django 3.0.5 on 2020-05-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0030_remove_comment_thread'),
        ('manager', '0004_delete_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='companyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.Company'),
        ),
    ]
