# Generated by Django 3.0.5 on 2020-05-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200520_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='companyName',
            new_name='company',
        ),
    ]
