# Generated by Django 3.0.5 on 2020-05-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20200520_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publicationTag',
            field=models.CharField(choices=[('INTERESTING', 'interesting'), ('IMPORTANT', 'important'), ('URGENTLY', 'urgently')], default='INTERESTING', max_length=11),
        ),
    ]
