# Generated by Django 3.0.3 on 2020-05-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20200520_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('userEmail', models.EmailField(max_length=50)),
                ('ukEmail', models.EmailField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('appointment', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('finished', models.BooleanField()),
            ],
        ),
    ]
