# Generated by Django 3.0.5 on 2020-05-22 13:25

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20200520_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publicationText',
            field=martor.models.MartorField(),
        ),
    ]
