# Generated by Django 3.0.5 on 2020-05-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0007_auto_20200522_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='donation_on',
            field=models.BooleanField(default=False),
        ),
    ]
