# Generated by Django 3.0.3 on 2020-05-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_news_district'),
        ('manager', '0007_regmanager'),
    ]

    operations = [
    ]
