# Generated by Django 3.0.5 on 2020-05-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_merge_20200528_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='regmanager',
            name='date',
            field=models.DateField(),
        ),
    ]
